# Generated by Django 4.2.7 on 2026-01-10 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('employee_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('office_area_sqm', models.FloatField(blank=True, help_text='Office area in square meters', null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESGInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_kwh', models.FloatField(blank=True, help_text='Monthly electricity in kWh', null=True)),
                ('electricity_bill_amount', models.FloatField(blank=True, help_text='Monthly electricity bill amount', null=True)),
                ('generator_usage_liters', models.FloatField(blank=True, help_text='Monthly generator fuel in liters', null=True)),
                ('generator_usage_hours', models.FloatField(blank=True, help_text='Monthly generator usage hours', null=True)),
                ('has_solar', models.BooleanField(default=False)),
                ('solar_capacity_kw', models.FloatField(blank=True, null=True)),
                ('water_source', models.CharField(choices=[('municipal', 'Municipal'), ('borehole', 'Borehole/Well'), ('both', 'Both'), ('other', 'Other')], default='municipal', max_length=50)),
                ('water_usage_liters', models.FloatField(blank=True, null=True)),
                ('waste_recycling', models.BooleanField(default=False)),
                ('waste_recycling_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('rarely', 'Rarely')], max_length=20, null=True)),
                ('waste_segregation', models.BooleanField(default=False)),
                ('total_employees', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('safety_training_provided', models.BooleanField(default=False)),
                ('safety_training_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('rarely', 'Rarely')], max_length=20, null=True)),
                ('employee_benefits', models.JSONField(default=list, help_text='List of benefits provided')),
                ('diversity_policy', models.BooleanField(default=False)),
                ('health_insurance', models.BooleanField(default=False)),
                ('code_of_conduct', models.BooleanField(default=False)),
                ('anti_corruption_policy', models.BooleanField(default=False)),
                ('data_privacy_policy', models.BooleanField(default=False)),
                ('whistleblower_policy', models.BooleanField(default=False)),
                ('board_oversight', models.BooleanField(default=False)),
                ('risk_management_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_inputs', to='esgapp.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ESGSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('social_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('governance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('overall_esg_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('data_completeness', models.FloatField(help_text='Percentage of data completeness', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_snapshots', to='esgapp.businessprofile')),
                ('esg_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='esgapp.esginput')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ESGScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_breakdown', to='esgapp.esgsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ESGRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(choices=[(1, 'Phase 1 (0-30 days)'), (2, 'Phase 2 (31-60 days)'), (3, 'Phase 3 (61-90 days)')])),
                ('action_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsible_role', models.CharField(max_length=100)),
                ('effort_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('esg_category', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='esgapp.esgsnapshot')),
            ],
            options={
                'ordering': ['phase', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ESGRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('E', 'Environmental'), ('S', 'Social'), ('G', 'Governance')], max_length=1)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('cost_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('expected_impact', models.TextField(help_text='Expected ESG impact description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='esgapp.esgsnapshot')),
            ],
            options={
                'ordering': ['priority', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='esgapp.esgsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='esgapp.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
