# Generated by Django 4.2.7 on 2026-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esginput',
            name='business_travel_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='carbon_footprint_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='charitable_contributions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='community_engagement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='customer_satisfaction_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='cybersecurity_measures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='employee_satisfaction_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='employee_training_hours',
            field=models.FloatField(blank=True, help_text='Average training hours per employee', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='energy_efficiency_measures',
            field=models.JSONField(default=list, help_text='LED lights, efficient AC, etc.'),
        ),
        migrations.AddField(
            model_name='esginput',
            name='esg_goals_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='esg_investment_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='esg_linked_executive_compensation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='female_employees_percentage',
            field=models.FloatField(blank=True, help_text='% of female employees', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='flexible_work_arrangements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='hazardous_waste_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='local_hiring_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='mental_health_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='paper_reduction_initiatives',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='product_safety_standards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='public_esg_commitments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='regulatory_compliance_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='remote_work_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='renewable_energy_percentage',
            field=models.FloatField(blank=True, help_text='% of renewable energy', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='stakeholder_engagement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='supplier_esg_requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='sustainability_reporting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='sustainable_finance_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='sustainable_procurement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='third_party_audits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='water_conservation_measures',
            field=models.JSONField(default=list, help_text='Water-saving devices, recycling'),
        ),
        migrations.AddField(
            model_name='esginput',
            name='workplace_accidents_last_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esginput',
            name='water_source',
            field=models.CharField(choices=[('municipal', 'Municipal'), ('borehole', 'Borehole/Well'), ('both', 'Both'), ('rainwater', 'Rainwater Harvesting'), ('other', 'Other')], default='municipal', max_length=50),
        ),
    ]
