# Generated by Django 4.2.7 on 2026-01-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgapp', '0002_esginput_business_travel_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgrecommendation',
            name='business_benefit',
            field=models.TextField(default='Improved ESG performance', help_text='Business benefits like cost savings, risk reduction'),
        ),
        migrations.AddField(
            model_name='esgrecommendation',
            name='esg_impact_points',
            field=models.CharField(default='+2 to +4 ESG points', help_text='Expected ESG score improvement', max_length=50),
        ),
        migrations.AddField(
            model_name='esgrecommendation',
            name='risk_reduction',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Risk reduction level', max_length=20),
        ),
        migrations.AddField(
            model_name='esgrecommendation',
            name='why_matters',
            field=models.TextField(blank=True, default='', help_text='Why this matters for this specific business'),
        ),
    ]
