# Generated by Django 4.2.7 on 2026-01-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgapp', '0003_esgrecommendation_business_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esginput',
            name='annual_revenue',
            field=models.FloatField(blank=True, help_text='Annual revenue in USD', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='board_diversity_percentage',
            field=models.FloatField(blank=True, help_text='% diverse board members', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='employee_turnover_rate',
            field=models.FloatField(blank=True, help_text='Annual employee turnover %', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='esg_budget_percentage',
            field=models.FloatField(blank=True, help_text='% of revenue allocated to ESG', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='esg_materiality_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='scope1_emissions',
            field=models.FloatField(blank=True, help_text='Direct emissions (tons CO2)', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='scope2_emissions',
            field=models.FloatField(blank=True, help_text='Indirect emissions (tons CO2)', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='scope3_emissions',
            field=models.FloatField(blank=True, help_text='Value chain emissions (tons CO2)', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='stakeholder_engagement_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('never', 'Never')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='supplier_esg_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esginput',
            name='waste_generated_tons',
            field=models.FloatField(blank=True, help_text='Total waste generated (tons/year)', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='waste_recycled_percentage',
            field=models.FloatField(blank=True, help_text='% of waste recycled', null=True),
        ),
        migrations.AddField(
            model_name='esginput',
            name='water_intensity',
            field=models.FloatField(blank=True, help_text='Water usage per revenue (L/USD)', null=True),
        ),
    ]
